### ISSUE TITLE
Error Hooking on Windows 10 64-bit

### ISSUE THREAD

**Issue by saverchenkov** [NytroRST/HookMe#1]
![image](https://user-images.githubusercontent.com/4248184/64491148-b689a480-d219-11e9-8cbf-a17fde00932f.png)

Greetings, Is there any way to access more detailed logs of what the issue is?

**Comment by NytroRST** [comment]
Hi,

I am not the author of the code, but the tool does not work on Google Chrome because Chrome does not use standard exported API functions to encrypt and decrypt the traffic. 

You can find here the hooked functions: https://github.com/NytroRST/HookMe/blob/b4ca66331bbf7d86d9121f44211a9a6a464ab24a/hookme/hook/Core/Hook.cs#L83

NetRipper used to hook Chrome, but I am pretty sure it does not work anymore because Chrome is constantly changing its code, but you can try it. 

Here you can find how hooking Chrome works: https://nytrosecurity.com/2018/02/26/hooking-chromes-ssl-functions/

**Comment by saverchenkov** [comment]
Apologies for a poor example. This happens in all applications. I am not actually trying to hook Chrome but something that uses proper winsock api, so it should technically work.

I rebuilt it from source in x64 and it works now. Thanks!

**Comment by ionutgpopescu** [comment]
Sounds good, I was also thinking it works on 32 bits only but I did not think it will easily work on x64, good job!
